<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CountriesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('countries')->truncate();

        $countries = [
            ['name' => 'Afghanistan', 'code' => 'AF', 'image' => '/images/countries/afghanistan.svg'],
            ['name' => 'Åland Islands', 'code' => 'AX', 'image' => '/images/countries/aland-islands.svg'],
            ['name' => 'Albania', 'code' => 'AL', 'image' => '/images/countries/albania.svg'],
            ['name' => 'Algeria', 'code' => 'DZ', 'image' => '/images/countries/algeria.svg'],
            ['name' => 'American Samoa', 'code' => 'AS', 'image' => '/images/countries/american-samoa.svg'],
            ['name' => 'Andorra', 'code' => 'AD', 'image' => '/images/countries/andorra.svg'],
            ['name' => 'Angola', 'code' => 'AO', 'image' => '/images/countries/angola.svg'],
            ['name' => 'Anguilla', 'code' => 'AI', 'image' => '/images/countries/anguilla.svg'],
            ['name' => 'Antarctica', 'code' => 'AQ', 'image' => '/images/countries/british-indian-ocean-territory.svg'],
            ['name' => 'Antigua and Barbuda', 'code' => 'AG', 'image' => '/images/countries/antigua-and-barbuda.svg'],
            ['name' => 'Argentina', 'code' => 'AR', 'image' => '/images/countries/argentina.svg'],
            ['name' => 'Armenia', 'code' => 'AM', 'image' => '/images/countries/armenia.svg'],
            ['name' => 'Aruba', 'code' => 'AW', 'image' => '/images/countries/aruba.svg'],
            ['name' => 'Australia', 'code' => 'AU', 'image' => '/images/countries/australia.svg'],
            ['name' => 'Austria', 'code' => 'AT', 'image' => '/images/countries/austria.svg'],
            ['name' => 'Azerbaijan', 'code' => 'AZ', 'image' => '/images/countries/azerbaijan.svg'],
            ['name' => 'Bahamas', 'code' => 'BS', 'image' => '/images/countries/bahamas.svg'],
            ['name' => 'Bahrain', 'code' => 'BH', 'image' => '/images/countries/bahrain.svg'],
            ['name' => 'Bangladesh', 'code' => 'BD', 'image' => '/images/countries/bangladesh.svg'],
            ['name' => 'Barbados', 'code' => 'BB', 'image' => '/images/countries/barbados.svg'],
            ['name' => 'Belarus', 'code' => 'BY', 'image' => '/images/countries/belarus.svg'],
            ['name' => 'Belgium', 'code' => 'BE', 'image' => '/images/countries/belgium.svg'],
            ['name' => 'Belize', 'code' => 'BZ', 'image' => '/images/countries/belize.svg'],
            ['name' => 'Benin', 'code' => 'BJ', 'image' => '/images/countries/benin.svg'],
            ['name' => 'Bermuda', 'code' => 'BM', 'image' => '/images/countries/bermuda.svg'],
            ['name' => 'Bhutan', 'code' => 'BT', 'image' => '/images/countries/bhutan.svg'],
            ['name' => 'Bolivia, Plurinational State of', 'code' => 'BO', 'image' => '/images/countries/bolivia.svg'],
            ['name' => 'Bonaire, Sint Eustatius and Saba', 'code' => 'BQ', 'image' => '/images/countries/bonaire.svg'],
            ['name' => 'Bosnia and Herzegovina', 'code' => 'BA', 'image' => '/images/countries/bosnia-and-herzegovina.svg'],
            ['name' => 'Botswana', 'code' => 'BW', 'image' => '/images/countries/botswana.svg'],
            ['name' => 'Bouvet Island', 'code' => 'BV', 'image' => '/images/countries/norway.svg'],
            ['name' => 'Brazil', 'code' => 'BR', 'image' => '/images/countries/brazil.svg'],
            ['name' => 'British Indian Ocean Territory', 'code' => 'IO', 'image' => '/images/countries/british-indian-ocean-territory.svg'],
            ['name' => 'Brunei Darussalam', 'code' => 'BN', 'image' => '/images/countries/brunei.svg'],
            ['name' => 'Bulgaria', 'code' => 'BG', 'image' => '/images/countries/bulgaria.svg'],
            ['name' => 'Burkina Faso', 'code' => 'BF', 'image' => '/images/countries/burkina-faso.svg'],
            ['name' => 'Burundi', 'code' => 'BI', 'image' => '/images/countries/burundi.svg'],
            ['name' => 'Cambodia', 'code' => 'KH', 'image' => '/images/countries/cambodia.svg'],
            ['name' => 'Cameroon', 'code' => 'CM', 'image' => '/images/countries/cameroon.svg'],
            ['name' => 'Canada', 'code' => 'CA', 'image' => '/images/countries/canada.svg'],
            ['name' => 'Cape Verde', 'code' => 'CV', 'image' => '/images/countries/cape-verde.svg'],
            ['name' => 'Cayman Islands', 'code' => 'KY', 'image' => '/images/countries/cayman-islands.svg'],
            ['name' => 'Central African Republic', 'code' => 'CF', 'image' => '/images/countries/central-african-republic.svg'],
            ['name' => 'Chad', 'code' => 'TD', 'image' => '/images/countries/chad.svg'],
            ['name' => 'Chile', 'code' => 'CL', 'image' => '/images/countries/chile.svg'],
            ['name' => 'China', 'code' => 'CN', 'image' => '/images/countries/china.svg'],
            ['name' => 'Christmas Island', 'code' => 'CX', 'image' => '/images/countries/christmas-island.svg'],
            ['name' => 'Cocos (Keeling) Islands', 'code' => 'CC', 'image' => '/images/countries/cocos-island.svg'],
            ['name' => 'Colombia', 'code' => 'CO', 'image' => '/images/countries/colombia.svg'],
            ['name' => 'Comoros', 'code' => 'KM', 'image' => '/images/countries/comoros.svg'],
            ['name' => 'Congo', 'code' => 'CG', 'image' => '/images/countries/democratic-republic-of-congo.svg'],
            ['name' => 'Congo, the Democratic Republic of the', 'code' => 'CD', 'image' => '/images/countries/democratic-republic-of-congo.svg'],
            ['name' => 'Cook Islands', 'code' => 'CK', 'image' => '/images/countries/cook-islands.svg'],
            ['name' => 'Costa Rica', 'code' => 'CR', 'image' => '/images/countries/costa-rica.svg'],
            ['name' => 'Côte d\'Ivoire', 'code' => 'CI', 'image' => '/images/countries/cape-verde.svg'],
            ['name' => 'Croatia', 'code' => 'HR', 'image' => '/images/countries/croatia.svg'],
            ['name' => 'Cuba', 'code' => 'CU', 'image' => '/images/countries/cuba.svg'],
            ['name' => 'Curaçao', 'code' => 'CW', 'image' => '/images/countries/curacao.svg'],
            ['name' => 'Cyprus', 'code' => 'CY', 'image' => '/images/countries/cyprus.svg'],
            ['name' => 'Czech Republic', 'code' => 'CZ', 'image' => '/images/countries/czech-republic.svg'],
            ['name' => 'Denmark', 'code' => 'DK', 'image' => '/images/countries/denmark.svg'],
            ['name' => 'Djibouti', 'code' => 'DJ', 'image' => '/images/countries/djibouti.svg'],
            ['name' => 'Dominica', 'code' => 'DM', 'image' => '/images/countries/dominica.svg'],
            ['name' => 'Dominican Republic', 'code' => 'DO', 'image' => '/images/countries/dominican-republic.svg'],
            ['name' => 'Ecuador', 'code' => 'EC', 'image' => '/images/countries/ecuador.svg'],
            ['name' => 'Egypt', 'code' => 'EG', 'image' => '/images/countries/egypt.svg'],
            ['name' => 'El Salvador', 'code' => 'SV', 'image' => '/images/countries/salvador.svg'],
            ['name' => 'Equatorial Guinea', 'code' => 'GQ', 'image' => '/images/countries/equatorial-guinea.svg'],
            ['name' => 'Eritrea', 'code' => 'ER', 'image' => '/images/countries/eritrea.svg'],
            ['name' => 'Estonia', 'code' => 'EE', 'image' => '/images/countries/estonia.svg'],
            ['name' => 'Ethiopia', 'code' => 'ET', 'image' => '/images/countries/ethiopia.svg'],
            ['name' => 'Falkland Islands (Malvinas)', 'code' => 'FK', 'image' => '/images/countries/falkland-islands.svg'],
            ['name' => 'Faroe Islands', 'code' => 'FO', 'image' => '/images/countries/faroe-islands.svg'],
            ['name' => 'Fiji', 'code' => 'FJ', 'image' => '/images/countries/fiji.svg'],
            ['name' => 'Finland', 'code' => 'FI', 'image' => '/images/countries/finland.svg'],
            ['name' => 'France', 'code' => 'FR', 'image' => '/images/countries/france.svg'],
            ['name' => 'French Guiana', 'code' => 'GF', 'image' => '/images/countries/france.svg'],
            ['name' => 'French Polynesia', 'code' => 'PF', 'image' => '/images/countries/french-polynesia.svg'],
            ['name' => 'French Southern Territories', 'code' => 'TF', 'image' => '/images/countries/france.svg'],
            ['name' => 'Gabon', 'code' => 'GA', 'image' => '/images/countries/gabon.svg'],
            ['name' => 'Gambia', 'code' => 'GM', 'image' => '/images/countries/gambia.svg'],
            ['name' => 'Georgia', 'code' => 'GE', 'image' => '/images/countries/georgia.svg'],
            ['name' => 'Germany', 'code' => 'DE', 'image' => '/images/countries/germany.svg'],
            ['name' => 'Ghana', 'code' => 'GH', 'image' => '/images/countries/ghana.svg'],
            ['name' => 'Gibraltar', 'code' => 'GI', 'image' => '/images/countries/gibraltar.svg'],
            ['name' => 'Greece', 'code' => 'GR', 'image' => '/images/countries/greece.svg'],
            ['name' => 'Greenland', 'code' => 'GL', 'image' => '/images/countries/greenland.svg'],
            ['name' => 'Grenada', 'code' => 'GD', 'image' => '/images/countries/grenada.svg'],
            ['name' => 'Guadeloupe', 'code' => 'GP', 'image' => '/images/countries/france.svg'],
            ['name' => 'Guam', 'code' => 'GU', 'image' => '/images/countries/guam.svg'],
            ['name' => 'Guatemala', 'code' => 'GT', 'image' => '/images/countries/guatemala.svg'],
            ['name' => 'Guernsey', 'code' => 'GG', 'image' => '/images/countries/guernsey.svg'],
            ['name' => 'Guinea', 'code' => 'GN', 'image' => '/images/countries/guinea.svg'],
            ['name' => 'Guinea-Bissau', 'code' => 'GW', 'image' => '/images/countries/guinea-bissau.svg'],
            ['name' => 'Guyana', 'code' => 'GY', 'image' => '/images/countries/guyana.svg'],
            ['name' => 'Haiti', 'code' => 'HT', 'image' => '/images/countries/haiti.svg'],
            ['name' => 'Heard Island and McDonald Mcdonald Islands', 'code' => 'HM', 'image' => '/images/countries/england.svg'],
            ['name' => 'Holy See (Vatican City State)', 'code' => 'VA', 'image' => '/images/countries/england.svg'],
            ['name' => 'Honduras', 'code' => 'HN', 'image' => '/images/countries/honduras.svg'],
            ['name' => 'Hong Kong', 'code' => 'HK', 'image' => '/images/countries/hong-kong.svg'],
            ['name' => 'Hungary', 'code' => 'HU', 'image' => '/images/countries/hungary.svg'],
            ['name' => 'Iceland', 'code' => 'IS', 'image' => '/images/countries/iceland.svg'],
            ['name' => 'India', 'code' => 'IN', 'image' => '/images/countries/india.svg'],
            ['name' => 'Indonesia', 'code' => 'ID', 'image' => '/images/countries/indonesia.svg'],
            ['name' => 'Iran, Islamic Republic of', 'code' => 'IR', 'image' => '/images/countries/iran.svg'],
            ['name' => 'Iraq', 'code' => 'IQ', 'image' => '/images/countries/iraq.svg'],
            ['name' => 'Ireland', 'code' => 'IE', 'image' => '/images/countries/ireland.svg'],
            ['name' => 'Isle of Man', 'code' => 'IM', 'image' => '/images/countries/isle-of-man.svg'],
            ['name' => 'Israel', 'code' => 'IL', 'image' => '/images/countries/israel.svg'],
            ['name' => 'Italy', 'code' => 'IT', 'image' => '/images/countries/italy.svg'],
            ['name' => 'Jamaica', 'code' => 'JM', 'image' => '/images/countries/jamaica.svg'],
            ['name' => 'Japan', 'code' => 'JP', 'image' => '/images/countries/japan.svg'],
            ['name' => 'Jersey', 'code' => 'JE', 'image' => '/images/countries/jersey.svg'],
            ['name' => 'Jordan', 'code' => 'JO', 'image' => '/images/countries/jordan.svg'],
            ['name' => 'Kazakhstan', 'code' => 'KZ', 'image' => '/images/countries/kazakhstan.svg'],
            ['name' => 'Kenya', 'code' => 'KE', 'image' => '/images/countries/kenya.svg'],
            ['name' => 'Kiribati', 'code' => 'KI', 'image' => '/images/countries/kiribati.svg'],
            ['name' => 'Korea, Democratic People\'s Republic of', 'code' => 'KP', 'image' => '/images/countries/south-korea.svg'],
            ['name' => 'Korea, Republic of', 'code' => 'KR', 'image' => '/images/countries/north-korea.svg'],
            ['name' => 'Kuwait', 'code' => 'KW', 'image' => '/images/countries/kuwait.svg'],
            ['name' => 'Kyrgyzstan', 'code' => 'KG', 'image' => '/images/countries/kyrgyzstan.svg'],
            ['name' => 'Lao People\'s Democratic Republic', 'code' => 'LA', 'image' => '/images/countries/laos.svg'],
            ['name' => 'Latvia', 'code' => 'LV', 'image' => '/images/countries/latvia.svg'],
            ['name' => 'Lebanon', 'code' => 'LB', 'image' => '/images/countries/lebanon.svg'],
            ['name' => 'Lesotho', 'code' => 'LS', 'image' => '/images/countries/lesotho.svg'],
            ['name' => 'Liberia', 'code' => 'LR', 'image' => '/images/countries/liberia.svg'],
            ['name' => 'Libya', 'code' => 'LY', 'image' => '/images/countries/libya.svg'],
            ['name' => 'Liechtenstein', 'code' => 'LI', 'image' => '/images/countries/liechtenstein.svg'],
            ['name' => 'Lithuania', 'code' => 'LT', 'image' => '/images/countries/lithuania.svg'],
            ['name' => 'Luxembourg', 'code' => 'LU', 'image' => '/images/countries/luxembourg.svg'],
            ['name' => 'Macao', 'code' => 'MO', 'image' => '/images/countries/macao.svg'],
            ['name' => 'Macedonia, the Former Yugoslav Republic of', 'code' => 'MK', 'image' => '/images/countries/republic-of-macedonia.svg'],
            ['name' => 'Madagascar', 'code' => 'MG', 'image' => '/images/countries/madagascar.svg'],
            ['name' => 'Malawi', 'code' => 'MW', 'image' => '/images/countries/malawi.svg'],
            ['name' => 'Malaysia', 'code' => 'MY', 'image' => '/images/countries/malaysia.svg'],
            ['name' => 'Maldives', 'code' => 'MV', 'image' => '/images/countries/maldives.svg'],
            ['name' => 'Mali', 'code' => 'ML', 'image' => '/images/countries/mali.svg'],
            ['name' => 'Malta', 'code' => 'MT', 'image' => '/images/countries/malta.svg'],
            ['name' => 'Marshall Islands', 'code' => 'MH', 'image' => '/images/countries/marshall-island.svg'],
            // ['name' => 'Martinique', 'code' => 'MQ'],
            // ['name' => 'Mauritania', 'code' => 'MR'],
            // ['name' => 'Mauritius', 'code' => 'MU'],
            // ['name' => 'Mayotte', 'code' => 'YT'],
            // ['name' => 'Mexico', 'code' => 'MX'],
            // ['name' => 'Micronesia, Federated States of', 'code' => 'FM'],
            // ['name' => 'Moldova, Republic of', 'code' => 'MD'],
            // ['name' => 'Monaco', 'code' => 'MC'],
            // ['name' => 'Mongolia', 'code' => 'MN'],
            // ['name' => 'Montenegro', 'code' => 'ME'],
            // ['name' => 'Montserrat', 'code' => 'MS'],
            // ['name' => 'Morocco', 'code' => 'MA'],
            // ['name' => 'Mozambique', 'code' => 'MZ'],
            // ['name' => 'Myanmar', 'code' => 'MM'],
            // ['name' => 'Namibia', 'code' => 'NA'],
            // ['name' => 'Nauru', 'code' => 'NR'],
            // ['name' => 'Nepal', 'code' => 'NP'],
            // ['name' => 'Netherlands', 'code' => 'NL'],
            // ['name' => 'New Caledonia', 'code' => 'NC'],
            // ['name' => 'New Zealand', 'code' => 'NZ'],
            // ['name' => 'Nicaragua', 'code' => 'NI'],
            // ['name' => 'Niger', 'code' => 'NE'],
            // ['name' => 'Nigeria', 'code' => 'NG'],
            // ['name' => 'Niue', 'code' => 'NU'],
            // ['name' => 'Norfolk Island', 'code' => 'NF'],
            // ['name' => 'Northern Mariana Islands', 'code' => 'MP'],
            // ['name' => 'Norway', 'code' => 'NO'],
            // ['name' => 'Oman', 'code' => 'OM'],
            // ['name' => 'Pakistan', 'code' => 'PK'],
            // ['name' => 'Palau', 'code' => 'PW'],
            // ['name' => 'Palestine, State of', 'code' => 'PS'],
            // ['name' => 'Panama', 'code' => 'PA'],
            // ['name' => 'Papua New Guinea', 'code' => 'PG'],
            // ['name' => 'Paraguay', 'code' => 'PY'],
            // ['name' => 'Peru', 'code' => 'PE'],
            // ['name' => 'Philippines', 'code' => 'PH'],
            // ['name' => 'Pitcairn', 'code' => 'PN'],
            // ['name' => 'Poland', 'code' => 'PL'],
            // ['name' => 'Portugal', 'code' => 'PT'],
            // ['name' => 'Puerto Rico', 'code' => 'PR'],
            // ['name' => 'Qatar', 'code' => 'QA'],
            // ['name' => 'Réunion', 'code' => 'RE'],
            // ['name' => 'Romania', 'code' => 'RO'],
            // ['name' => 'Russian Federation', 'code' => 'RU'],
            // ['name' => 'Rwanda', 'code' => 'RW'],
            // ['name' => 'Saint Barthélemy', 'code' => 'BL'],
            // ['name' => 'Saint Helena, Ascension and Tristan da Cunha', 'code' => 'SH'],
            // ['name' => 'Saint Kitts and Nevis', 'code' => 'KN'],
            // ['name' => 'Saint Lucia', 'code' => 'LC'],
            // ['name' => 'Saint Martin (French part)', 'code' => 'MF'],
            // ['name' => 'Saint Pierre and Miquelon', 'code' => 'PM'],
            // ['name' => 'Saint Vincent and the Grenadines', 'code' => 'VC'],
            // ['name' => 'Samoa', 'code' => 'WS'],
            // ['name' => 'San Marino', 'code' => 'SM'],
            // ['name' => 'Sao Tome and Principe', 'code' => 'ST'],
            // ['name' => 'Saudi Arabia', 'code' => 'SA'],
            // ['name' => 'Senegal', 'code' => 'SN'],
            // ['name' => 'Serbia', 'code' => 'RS'],
            // ['name' => 'Seychelles', 'code' => 'SC'],
            // ['name' => 'Sierra Leone', 'code' => 'SL'],
            // ['name' => 'Singapore', 'code' => 'SG'],
            // ['name' => 'Sint Maarten (Dutch part)', 'code' => 'SX'],
            // ['name' => 'Slovakia', 'code' => 'SK'],
            // ['name' => 'Slovenia', 'code' => 'SI'],
            // ['name' => 'Solomon Islands', 'code' => 'SB'],
            // ['name' => 'Somalia', 'code' => 'SO'],
            // ['name' => 'South Africa', 'code' => 'ZA'],
            // ['name' => 'South Georgia and the South Sandwich Islands', 'code' => 'GS'],
            // ['name' => 'South Sudan', 'code' => 'SS'],
            // ['name' => 'Spain', 'code' => 'ES'],
            // ['name' => 'Sri Lanka', 'code' => 'LK'],
            // ['name' => 'Sudan', 'code' => 'SD'],
            // ['name' => 'Suriname', 'code' => 'SR'],
            // ['name' => 'Svalbard and Jan Mayen', 'code' => 'SJ'],
            // ['name' => 'Swaziland', 'code' => 'SZ'],
            // ['name' => 'Sweden', 'code' => 'SE'],
            // ['name' => 'Switzerland', 'code' => 'CH'],
            // ['name' => 'Syrian Arab Republic', 'code' => 'SY'],
            // ['name' => 'Taiwan', 'code' => 'TW'],
            // ['name' => 'Tajikistan', 'code' => 'TJ'],
            // ['name' => 'Tanzania, United Republic of', 'code' => 'TZ'],
            // ['name' => 'Thailand', 'code' => 'TH'],
            // ['name' => 'Timor-Leste', 'code' => 'TL'],
            // ['name' => 'Togo', 'code' => 'TG'],
            // ['name' => 'Tokelau', 'code' => 'TK'],
            // ['name' => 'Tonga', 'code' => 'TO'],
            // ['name' => 'Trinidad and Tobago', 'code' => 'TT'],
            // ['name' => 'Tunisia', 'code' => 'TN'],
            // ['name' => 'Turkey', 'code' => 'TR'],
            // ['name' => 'Turkmenistan', 'code' => 'TM'],
            // ['name' => 'Turks and Caicos Islands', 'code' => 'TC'],
            // ['name' => 'Tuvalu', 'code' => 'TV'],
            // ['name' => 'Uganda', 'code' => 'UG'],
            // ['name' => 'Ukraine', 'code' => 'UA'],
            // ['name' => 'United Arab Emirates', 'code' => 'AE'],
            // ['name' => 'United Kingdom', 'code' => 'GB'],
            // ['name' => 'United States', 'code' => 'US'],
            // ['name' => 'United States Minor Outlying Islands', 'code' => 'UM'],
            // ['name' => 'Uruguay', 'code' => 'UY'],
            // ['name' => 'Uzbekistan', 'code' => 'UZ'],
            // ['name' => 'Vanuatu', 'code' => 'VU'],
            // ['name' => 'Venezuela, Bolivarian Republic of', 'code' => 'VE'],
            // ['name' => 'Viet Nam', 'code' => 'VN'],
            // ['name' => 'Virgin Islands, British', 'code' => 'VG'],
            // ['name' => 'Virgin Islands, U.S.', 'code' => 'VI'],
            // ['name' => 'Wallis and Futuna', 'code' => 'WF'],
            // ['name' => 'Western Sahara', 'code' => 'EH'],
            // ['name' => 'Yemen', 'code' => 'YE'],
            // ['name' => 'Zambia', 'code' => 'ZM'],
            // ['name' => 'Zimbabwe', 'code' => 'ZW'],
        ];

        DB::table('countries')->insert($countries);
    }
}
